[package]
name = "dcm_io_derive"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "3", features = ["extra-traits"] }
quote = "1"
proc-macro2 = "1"
dcm_io = { path = "../dcm_io" }
dicom-core.workspace = true
dicom-object.workspace = true

[lib]
proc-macro = true

[[test]]
name = "parse_str"
path = "tests/parse_str.rs"

[[test]]
name = "parse_tag"
path = "tests/parse_tag.rs"

[[test]]
name = "parse_date"
path = "tests/parse_date.rs"

[[test]]
name = "parse_time"
path = "tests/parse_time.rs"

[[test]]
name = "parse_datetime"
path = "tests/parse_datetime.rs"

[[test]]
name = "parse_f32"
path = "tests/parse_f32.rs"

[[test]]
name = "parse_f64"
path = "tests/parse_f64.rs"

[[test]]
name = "parse_int_string"
path = "tests/parse_int_string.rs"