[package]
name = "dcm_io_derive"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "3", features = ["extra-traits"] }
quote = "1"
proc-macro2 = "1"
dcm_io = {path = "../dcm_io"}
dicom-core.workspace = true
dicom-object.workspace = true

[lib]
proc-macro = true


[[test]]
name = "parse_01"
path = "tests/parse_01.rs"